name: Deployment

on:
  push:
    branches: [ "master" ]

env:
  NODE_VERSION: '18.12.1'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_FIREBASE_KEY: ${{ secrets.VITE_FIREBASE_KEY }}
      VITE_FIREBASE_DOMAIN: ${{ secrets.VITE_FIREBASE_DOMAIN }}
      VITE_FIREBASE_DATABASE: ${{ secrets.VITE_FIREBASE_DATABASE }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_BUCKET: ${{ secrets.VITE_FIREBASE_BUCKET }}
      VITE_FIREBASE_SENDER_ID: ${{ secrets.VITE_FIREBASE_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      VITE_BASE_API_URL: ${{ vars.VITE_BASE_API_URL }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Yarn Install
      uses: Borales/actions-yarn@v4.2.0
      with:
          cmd: install

    - name: npm build
      run: |
        npm run lint 
        npm run build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: dist

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment: 'production'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
        
    - name: SSH - Clear previous deployment
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        # Remove all files inside of it, silence errors like "no files found to delete"
        script: rm -r ${{ secrets.FTP_DIST_DIR }}/* | exit 0

        
    - name: SFTP - Deploy website
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USER }}
        server: ${{ secrets.FTP_HOST }}
        port: 22
        local_path: './*'
        remote_path: ${{ secrets.FTP_DIST_DIR }}/
        sftp_only: true
        password: ${{ secrets.FTP_PASSWORD }}


      
